// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    Counter: typeof import('./common/components/Counter.vue')['default']
    DarkSwitch: typeof import('./common/components/DarkSwitch.vue')['default']
    DeviceCard: typeof import('./dashboard/components/device/DeviceCard.vue')['default']
    DeviceHistory: typeof import('./dashboard/components/device/DeviceHistory.vue')['default']
    DevicesList: typeof import('./dashboard/components/device/DevicesList.vue')['default']
    DevicesMap: typeof import('./dashboard/components/DevicesMap.vue')['default']
    Footer: typeof import('./common/components/Footer.vue')['default']
    GMapDevices: typeof import('./dashboard/components/GMapDevices.vue')['default']
    LayoutHeader: typeof import('./common/components/ayout/LayoutHeader.vue')['default']
    LayoutSider: typeof import('./common/components/ayout/LayoutSider.vue')['default']
    Map: typeof import('./common/components/Map.vue')['default']
    README: typeof import('./common/components/README.md')['default']
  }
}

export { }
