// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABadgeRibbon: typeof import('ant-design-vue/es')['BadgeRibbon']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect']
    Counter: typeof import('./common/components/Counter.vue')['default']
    DarkSwitch: typeof import('./common/components/DarkSwitch.vue')['default']
    DeviceCard: typeof import('./dashboard/components/device/DeviceCard.vue')['default']
    DeviceFormModal: typeof import('./dashboard/components/device/DeviceFormModal.vue')['default']
    DeviceHistory: typeof import('./dashboard/components/device/DeviceHistory.vue')['default']
    DeviceHistoryStatistics: typeof import('./dashboard/components/device/DeviceHistoryStatistics.vue')['default']
    DeviceInfos: typeof import('./dashboard/components/device/DeviceInfos.vue')['default']
    DevicesList: typeof import('./dashboard/components/device/DevicesList.vue')['default']
    DevicesMap: typeof import('./dashboard/components/DevicesMap.vue')['default']
    Footer: typeof import('./common/components/Footer.vue')['default']
    GMapDevices: typeof import('./dashboard/components/GMapDevices.vue')['default']
    LayoutHeader: typeof import('./common/components/ayout/LayoutHeader.vue')['default']
    LayoutSider: typeof import('./common/components/ayout/LayoutSider.vue')['default']
    Map: typeof import('./common/components/Map.vue')['default']
    README: typeof import('./common/components/README.md')['default']
  }
}

export { }
